# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy container app to Azure Web App - mi-pwa-tareas-app-final

on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  build:
    runs-on: 'ubuntu-latest'

    steps:
    - uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Log in to registry
      uses: docker/login-action@v2
      with:
        registry: https://gayetopwacontainer.azurecr.io/
        username: ${{ secrets.AzureAppService_ContainerUsername_eb47207c93464ddca3ecd2dbb6b07305 }}
        password: ${{ secrets.AzureAppService_ContainerPassword_7132384f760f4c4d80e43e60a20c8ab3 }}

    - name: Build and push container image to registry
      uses: docker/build-push-action@v3
      with:
        push: true
        tags: gayetopwacontainer.azurecr.io/${{ secrets.AzureAppService_ContainerUsername_eb47207c93464ddca3ecd2dbb6b07305 }}/mi-pwa-tareas-app:${{ github.sha }}
        file: ./Dockerfile

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
    - name: Deploy to Azure Web App
      id: deploy-to-webapp
      uses: azure/webapps-deploy@v2
      with:
        app-name: 'mi-pwa-tareas-app-final'
        slot-name: 'production'
        publish-profile: ${{ secrets.AzureAppService_PublishProfile_c5519af0959e4fb1aa879fd8bfe2b284 }}
        images: 'gayetopwacontainer.azurecr.io/${{ secrets.AzureAppService_ContainerUsername_eb47207c93464ddca3ecd2dbb6b07305 }}/mi-pwa-tareas-app:${{ github.sha }}'